### ISSUE TITLE
ダミーデータを突っ込めるdumpタスク的なの欲しい

### ISSUE THREAD

**Issue by sawa-zen** [topotal/blog#16]

**Comment by rrreeeyyy** [comment]
`bundle exec rake db:fixtures:load` ?

**Comment by sawa-zen** [comment]
おっと。すでにござる？

**Comment by rrreeeyyy** [comment]
入れるダミーデータはないけどタスクはある

**Comment by sawa-zen** [comment]
じゃあ俺でもデータの追加可能？

**Comment by sawa-zen** [comment]
http://qiita.com/itkrt2y/items/ca34fea17fc7dde56b7a
これやりゃいいのか。yay
