### ISSUE TITLE
usersテーブルにカラムを追加したい

### ISSUE THREAD

**Issue by sawa-zen** [topotal/blog#29]
ユーザー情報に以下の項目を追加したいです。
お手数ですがお願い致します。

|key|type|example|
|---|---|---|
|name|String|'澤田 嵩善'|
|description|String|'自己紹介文です。自己紹介文です'|
|icon_image_url|String|'/assets/img/upload/hogehoge'|

**Comment by sawa-zen** [comment]
あ、あとプローフィール写真の画像パスも欲しい

**Comment by sawa-zen** [comment]
key名は仮のものなのでそちらできれいな形に変更してもらって大丈夫です。

**Comment by nari-ex** [comment]
ユーザープロファイル用のAPIを作ることで対処した感じ↑

@sawa-zen ユーザー用の画像は記事用の画像とは別で管理します。ユーザプロファイル更新時は一欄から選ぶのではなくプロファイル用の画像を都度アップロードすることを想定してます。
