### ISSUE TITLE
access token を更新できるようにする

### ISSUE THREAD

**Issue by sawa-zen** [topotal/blog#31]
> 多分 expire の長い refresh token を作って払い出した上で access token を更新できるようにすると思う
> なるべくセキュアな方法を考える

**Comment by sawa-zen** [comment]
最後にAPI叩いたタイミングから3日とか時間がたってたらtokenを向こうにするとかの方法だとだめなんかな？

**Comment by rrreeeyyy** [comment]
取り急ぎ 8 時間にしたんでまた不便だったらいってください @sawa-zen
